import type { Metadata } from "next";
import PublicPage from "@/components/layout/PublicPage";
import { EditorialCardGrid, EditorialContinuation, type EditorialCardItem } from "@/components/discovery/EditorialCards";
import InspirationSurface from "@/components/discovery/InspirationSurface";
export const metadata: Metadata = { title: "Travel Inspiration", description: "Thoughtful ideas for journeys that feel personal." };
const themes: EditorialCardItem[] = [
  { title: "Journeys built around a feeling", label: "Begin with why", copy: "You may be looking to reconnect, celebrate, pause or simply see the world from a different angle.", image: "/images/travel-inspiration/feeling-led-journey.webp", alt: "A traveller journalling on a quiet hill-town veranda in the morning mist", prompt: "How would you like this journey to feel?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
  { title: "Slow and unhurried travel", label: "A different rhythm", copy: "Choose fewer places, stay a little longer and leave enough room for a journey to unfold naturally.", image: "/images/journey-passport/travel-styles/relaxation.webp", alt: "Peaceful travel setting for a slower journey", prompt: "What could you leave unplanned?", passportHref: "/journey-passport?inspiration=Relaxation", passportLabel: "Begin with this inspiration" },
  { title: "Meaningful family time", label: "Time together", copy: "The right journey creates room for easy laughter, shared discoveries and moments across generations.", image: "/images/journey-passport/companions/family.webp", alt: "Family sharing time while travelling", prompt: "Who do you want beside you?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
  { title: "Short escapes that restore", label: "A thoughtful pause", copy: "A weekend away can bring a little perspective when everyday life has become too full.", image: "/images/journey-passport/timing/within-next-month.webp", alt: "Traveller preparing for a restorative short escape", prompt: "What would help you reset?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
  { title: "Food, culture and local connection", label: "A sense of place", copy: "Follow the flavours, stories and everyday rituals that make a place feel lived in rather than simply visited.", image: "/images/journey-passport/travel-styles/food-dining.webp", alt: "Local food and dining travel inspiration", prompt: "What would you like to taste or learn?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
  { title: "Nature-led journeys", label: "Space to breathe", copy: "Let landscapes, water, wildlife and wide horizons set a gentler pace for the days ahead.", image: "/images/journey-passport/travel-styles/nature.webp", alt: "Natural landscape for a nature-led journey", prompt: "Where do you feel most restored?", passportHref: "/journey-passport?inspiration=Wildlife", passportLabel: "Begin with this inspiration" },
  { title: "Celebrations worth travelling for", label: "Mark the moment", copy: "Some occasions deserve a setting that helps everyone slow down and remember why they came together.", image: "/images/journey-passport/travel-styles/celebrations.webp", alt: "Travellers celebrating a special occasion", prompt: "What would make the moment feel special?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
  { title: "A first international journey", label: "A new perspective", copy: "The right first journey abroad balances excitement with the reassurance of thoughtful planning and personal support.", image: "/images/journey-passport/dream-journeys/city-discovery.webp", alt: "Traveller exploring an international city", prompt: "What would help you travel with confidence?", passportHref: "/journey-passport", passportLabel: "Begin with this inspiration" },
];
export default function InspirationPage(){return <PublicPage eyebrow="Travel Inspiration" title="What possibilities might you not have considered?" intro="A good journey often starts with a feeling. Let these ideas help you notice what you may be ready for."><InspirationSurface className="layout-section"><div className="layout-container"><div className="layout-section-heading mb-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2A211C]">A place to imagine</p><h2 className="mt-4 text-balance font-serif text-4xl leading-[1.08] tracking-[-.04em] sm:text-5xl">Not a catalogue. A few ways a journey could feel.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#2A211C]">These are ideas, not fixed itineraries. A Journey Designer can help decide which possibility is right for your story.</p></div><EditorialCardGrid items={themes}/></div></InspirationSurface><EditorialContinuation eyebrow="Your next possibility" title="Let us begin with what matters to you." copy="Share the feeling, people and timing behind your journey. Your Journey Director will help you discover a considered next step." label="Discover My Possibilities" closingChapter/></PublicPage>}
