"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

const invitations = [
  { title: "Memory Makers", copy: "For the moments you will revisit long after you return home.", image: "/images/journey-passport/travel-styles/photography.webp", alt: "Traveller capturing a meaningful travel memory" },
  { title: "Celebration Moments", copy: "For milestones that deserve more than an ordinary backdrop.", image: "/images/journey-passport/travel-styles/celebrations.webp", alt: "Travellers sharing a celebration" },
  { title: "Family Time", copy: "For making room for the people who matter most.", image: "/images/journey-passport/companions/family.webp", alt: "Family spending time together while travelling" },
  { title: "Global Escapes", copy: "For the joy of stepping into a world that feels wonderfully new.", image: "/images/journey-passport/dream-journeys/city-discovery.webp", alt: "Traveller discovering a new city" },
  { title: "Nature & Serenity", copy: "For slower mornings, open views and a little room to breathe.", image: "/images/journey-passport/travel-styles/nature.webp", alt: "Quiet natural landscape for a slower journey" },
  { title: "Weekend Getaways", copy: "For a thoughtful pause when a few days can change your rhythm.", image: "/images/journey-passport/timing/within-next-month.webp", alt: "Traveller preparing for a short escape" },
] as const;

const destinations = [
  { name: "Kashmir", region: "India · Mountains & valleys", copy: "For cool air, wide landscapes and a complete change of pace.", image: "/images/journey-passport/dream-journeys/mountain-retreat.webp" },
  { name: "Kerala", region: "India · Backwaters & hills", copy: "For unhurried days shaped by water, green space and gentle comfort.", image: "/images/journey-director/kerala-alleppey-golden-hour.jpg" },
  { name: "Rajasthan", region: "India · Culture & heritage", copy: "For colour, history and stories that unfold at their own pace.", image: "/images/journey-passport/travel-styles/culture-heritage.webp" },
  { name: "Andaman", region: "India · Islands & coast", copy: "For clear horizons and time spent close to the sea.", image: "/images/journey-passport/travel-styles/beaches-islands.webp" },
  { name: "Bali", region: "Indonesia · Ritual & renewal", copy: "For warm light, generous culture and moments of quiet discovery.", image: "/images/journey-director/bali-ubud-golden-hour.jpg" },
  { name: "Dubai", region: "United Arab Emirates · City & desert", copy: "For polished stays, striking contrasts and celebratory energy.", image: "/images/journey-passport/dream-journeys/city-discovery.webp" },
  { name: "Singapore", region: "Singapore · City & gardens", copy: "For an easy rhythm of food, design and green spaces.", image: "/images/journey-passport/travel-styles/food-dining.webp" },
  { name: "Vietnam", region: "Vietnam · Culture & discovery", copy: "For layered stories, vivid flavours and journeys full of perspective.", image: "/images/journey-passport/travel-styles/adventure.webp" },
] as const;

const trustPoints = [
  { icon: "◌", title: "We listen before recommending", copy: "Your reason for travelling matters before any destination is suggested." },
  { icon: "✦", title: "Every journey is thoughtfully designed", copy: "We shape possibilities around the people, pace and moments that matter." },
  { icon: "↗", title: "Honest advice over quick sales", copy: "We are clear about what fits, what needs checking and where a compromise exists." },
  { icon: "◎", title: "Personal support from your Journey Designer", copy: "A real person remains responsible for turning a possibility into a considered plan." },
] as const;

const inspiration = [
  { title: "Hidden sunrise experiences", copy: "Start a day somewhere still enough to remember it properly.", image: "/images/journey-passport/travel-styles/photography.webp" },
  { title: "Family-friendly escapes", copy: "Create room for every generation to enjoy the journey together.", image: "/images/journey-passport/companions/family.webp" },
  { title: "Slow travel ideas", copy: "Choose fewer places, stay a little longer and let the journey unfold.", image: "/images/journey-passport/travel-styles/relaxation.webp" },
  { title: "Weekend inspiration", copy: "A short change of scene can be the beginning of something restorative.", image: "/images/journey-passport/timing/within-next-month.webp" },
] as const;

export default function HomepageExperience() {
  const [invitationNotice, setInvitationNotice] = useState("");

  return (
    <div className="bg-[#fbf7ef] text-[#2d2117]">
      <section className="px-6 py-20 sm:px-8 lg:px-10 lg:py-28" aria-labelledby="journey-invitations-heading">
        <div className="mx-auto max-w-7xl">
          <div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#96652b]">Begin with what matters</p><h2 id="journey-invitations-heading" className="mt-4 text-balance font-serif text-4xl leading-[1.03] tracking-[-0.045em] sm:text-5xl">What kind of time are you hoping to make?</h2><p className="mt-5 text-lg leading-8 text-[#705c47]">You do not need every detail yet. Begin with the feeling, the people or the moment that is calling you.</p></div>
          <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {invitations.map((invitation, index) => <article key={invitation.title} className={`group relative min-h-[25rem] overflow-hidden rounded-[2rem] bg-[#2d2117] shadow-[0_18px_45px_rgba(86,55,22,0.14)] ${index === 0 ? "md:col-span-2 lg:col-span-1" : ""}`}><Image src={invitation.image} alt={invitation.alt} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(28,17,9,.9),rgba(28,17,9,.15)_75%)]" aria-hidden="true"/><div className="absolute inset-x-0 bottom-0 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#f3c681]">A journey invitation</p><h3 className="mt-3 font-serif text-3xl tracking-[-0.04em]">{invitation.title}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/85">{invitation.copy}</p><button type="button" onClick={() => setInvitationNotice(`${invitation.title} is a starting point for your Journey Passport.`)} className="mt-6 text-sm font-bold text-[#f3c681] transition hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f3c681]">Explore this experience <span aria-hidden="true">→</span></button></div></article>)}
          </div>
          <p className="sr-only" role="status" aria-live="polite">{invitationNotice}</p>
        </div>
      </section>

      <section className="bg-[#f1e4cf] px-6 py-20 sm:px-8 lg:px-10 lg:py-28" aria-labelledby="destinations-heading"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#96652b]">Places with possibility</p><h2 id="destinations-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-0.045em] sm:text-5xl">Some places are worth beginning with.</h2></div><p className="max-w-md leading-7 text-[#705c47]">These are not packages or promises. They are thoughtful starting points for a conversation about what could fit.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{destinations.map((destination)=><article key={destination.name} className="group overflow-hidden rounded-[1.5rem] bg-[#2d2117] shadow-[0_14px_35px_rgba(84,52,17,.14)]"><div className="relative aspect-[4/5]"><Image src={destination.image} alt={`Travel inspiration for ${destination.name}`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(28,17,9,.88),transparent_78%)]" aria-hidden="true"/><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-[0.68rem] font-bold uppercase tracking-[.14em] text-[#f3c681]">{destination.region}</p><h3 className="mt-2 font-serif text-3xl">{destination.name}</h3><p className="mt-2 text-sm leading-6 text-white/82">{destination.copy}</p><Link href="/destinations" className="mt-4 inline-flex text-sm font-bold text-[#f3c681] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#f3c681]">Discover destination <span aria-hidden="true" className="ml-2">→</span></Link></div></div></article>)}</div></div></section>

      <section className="px-6 py-20 sm:px-8 lg:px-10 lg:py-28" aria-labelledby="trust-heading"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.5fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#96652b]">Travel confidence</p><h2 id="trust-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-0.045em] sm:text-5xl">A journey begins with being understood.</h2><p className="mt-6 leading-8 text-[#705c47]">We do not begin with what is easiest to sell. We begin with the person taking the journey.</p></div><div className="grid gap-4 sm:grid-cols-2">{trustPoints.map((point)=><article key={point.title} className="rounded-[1.5rem] border border-[#e4d2b5] bg-white p-7 shadow-[0_10px_28px_rgba(91,55,18,.06)]"><span aria-hidden="true" className="grid size-11 place-items-center rounded-full bg-[#f5e4c5] text-xl text-[#986328]">{point.icon}</span><h3 className="mt-6 text-xl font-semibold tracking-[-.02em]">{point.title}</h3><p className="mt-3 text-sm leading-7 text-[#705c47]">{point.copy}</p></article>)}</div></div></section>

      <section className="bg-[#2d2117] px-6 py-20 text-white sm:px-8 lg:px-10 lg:py-28" aria-labelledby="inspiration-heading"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#f3c681]">Travel inspiration</p><h2 id="inspiration-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-0.045em] sm:text-5xl">A few ideas to carry with you.</h2><p className="mt-5 text-lg leading-8 text-white/70">Inspiration is not an itinerary. It is a way to notice the kind of experience you may be ready for.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{inspiration.map((item)=><article key={item.title} className="group overflow-hidden rounded-[1.5rem] border border-white/15 bg-white/5"><div className="relative aspect-[4/3]"><Image src={item.image} alt={`Travel inspiration: ${item.title}`} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/></div><div className="p-6"><h3 className="font-serif text-2xl">{item.title}</h3><p className="mt-3 text-sm leading-6 text-white/70">{item.copy}</p></div></article>)}</div><Link href="/travel-inspiration" className="mt-10 inline-flex rounded-full border border-[#f3c681] px-6 py-3 text-sm font-bold text-[#f3c681] transition hover:bg-[#f3c681] hover:text-[#2d2117] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">Explore inspiration <span aria-hidden="true" className="ml-2">→</span></Link></div></section>

      <section className="px-6 py-20 sm:px-8 lg:px-10 lg:py-28" aria-labelledby="about-preview-heading"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[2rem] bg-[linear-gradient(125deg,#f6e2bd,#fffaf0_55%,#ead6b1)] lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 sm:p-12 lg:p-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#96652b]">Our promise to you</p><h2 id="about-preview-heading" className="mt-4 max-w-xl font-serif text-4xl leading-[1.03] tracking-[-.045em] sm:text-5xl">More Than a Trip. It’s an Experience.</h2><p className="mt-6 max-w-xl leading-8 text-[#705c47]">Every traveller is unique. Every journey should be too. We listen before selling, guide honestly and keep people at the centre of every decision.</p><Link href="/about" className="mt-8 inline-flex rounded-full bg-[#a86f29] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#83521a] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#a86f29]">Learn more about us <span aria-hidden="true" className="ml-2">→</span></Link></div><div className="relative min-h-[20rem]"><Image src="/images/golden-hour.png" alt="Travellers sharing a golden-hour moment" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover"/></div></div></section>

      <section className="bg-[#f1e4cf] px-6 py-20 sm:px-8 lg:px-10 lg:py-28" aria-labelledby="contact-preview-heading"><div className="mx-auto grid max-w-7xl gap-10 rounded-[2rem] bg-white p-8 shadow-[0_14px_40px_rgba(86,55,22,.08)] sm:p-12 lg:grid-cols-[1.05fr_.95fr] lg:p-16"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#96652b]">Begin a conversation</p><h2 id="contact-preview-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-.045em] sm:text-5xl">When you are ready, we are here.</h2><p className="mt-5 max-w-xl leading-8 text-[#705c47]">Tell us what is on your mind. A Journey Designer can help you take the next thoughtful step.</p><Link href="/journey-passport" className="mt-8 inline-flex rounded-full bg-[#a86f29] px-7 py-3 text-sm font-bold text-white transition hover:bg-[#83521a] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#a86f29]">Start planning your journey <span aria-hidden="true" className="ml-2">→</span></Link></div><address className="not-italic text-[#705c47]"><dl className="grid gap-5"><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#96652b]">WhatsApp</dt><dd className="mt-1"><a href="https://wa.me/918925838541" className="font-semibold text-[#2d2117] underline decoration-[#d5a665] underline-offset-4">+91 89258 38541</a></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#96652b]">Phone</dt><dd className="mt-1"><a href="tel:+918925838541" className="font-semibold text-[#2d2117] underline decoration-[#d5a665] underline-offset-4">+91 89258 38541</a></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#96652b]">Email</dt><dd className="mt-1"><a href="mailto:bookings@searchmyvacation.com" className="font-semibold text-[#2d2117] underline decoration-[#d5a665] underline-offset-4">bookings@searchmyvacation.com</a></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#96652b]">Office hours</dt><dd className="mt-1">Monday–Saturday<br/>10:00 AM–7:00 PM IST</dd></div></dl></address></div></section>
    </div>
  );
}
