"use client";

import Image from "next/image";
import Link from "next/link";
import WhatsAppLink from "@/components/contact/WhatsAppLink";
import InspirationSurface from "@/components/discovery/InspirationSurface";
import TravellerStories from "@/components/sections/TravellerStories";
import { siteContact } from "@/config/contact.config";
import { journeyCanonicalImage } from "@/config/destination-images.config";

const invitations = [
  { title: "Memory Makers", copy: "For the moments you will revisit long after you return home.", image: "/images/journey-passport/travel-styles/photography.webp", alt: "Traveller capturing a meaningful travel memory" },
  { title: "Celebration Moments", copy: "For milestones that deserve more than an ordinary backdrop.", image: "/images/journey-passport/travel-styles/celebrations.webp", alt: "Travellers sharing a celebration" },
  { title: "Family Time", copy: "For making room for the people who matter most.", image: "/images/journey-passport/companions/family.webp", alt: "Family spending time together while travelling" },
  { title: "Global Escapes", copy: "For the joy of stepping into a world that feels wonderfully new.", image: "/images/journey-passport/dream-journeys/city-discovery.webp", alt: "Traveller discovering a new city" },
  { title: "Nature & Serenity", copy: "For slower mornings, open views and a little room to breathe.", image: "/images/journey-passport/travel-styles/nature.webp", alt: "Quiet natural landscape for a slower journey" },
  { title: "Weekend Getaways", copy: "For a thoughtful pause when a few days can change your rhythm.", image: "/images/journey-passport/timing/within-next-month.webp", alt: "Traveller preparing for a short escape" },
] as const;

const homepageInvitations = invitations.slice(0, 3);

const destinations = [
  { name: "Kashmir", slug: "kashmir", region: "India · Mountains & valleys", copy: "For cool air, wide landscapes and a complete change of pace.", image: journeyCanonicalImage("kashmir").heroImage },
  { name: "Kerala", slug: "kerala", region: "India · Backwaters & hills", copy: "For unhurried days shaped by water, green space and gentle comfort.", image: journeyCanonicalImage("kerala").heroImage },
  { name: "Rajasthan", slug: "rajasthan", region: "India · Culture & heritage", copy: "For colour, history and stories that unfold at their own pace.", image: journeyCanonicalImage("rajasthan").heroImage },
  { name: "Andaman", slug: "andaman", region: "India · Islands & coast", copy: "For clear horizons and time spent close to the sea.", image: journeyCanonicalImage("andaman").heroImage },
  { name: "Bali", slug: "bali", region: "Indonesia · Ritual & renewal", copy: "For warm light, generous culture and moments of quiet discovery.", image: journeyCanonicalImage("bali").heroImage },
  { name: "Dubai", slug: "dubai", region: "United Arab Emirates · City & desert", copy: "For polished stays, striking contrasts and celebratory energy.", image: journeyCanonicalImage("dubai").heroImage },
  { name: "Singapore", slug: "singapore", region: "Singapore · City & gardens", copy: "For an easy rhythm of food, design and green spaces.", image: journeyCanonicalImage("singapore").heroImage },
  { name: "Vietnam", slug: "vietnam", region: "Vietnam · Culture & discovery", copy: "For layered stories, vivid flavours and journeys full of perspective.", image: journeyCanonicalImage("vietnam").heroImage },
] as const;

const trustPoints = [
  { icon: "◌", title: "We listen before recommending", copy: "Your reason for travelling matters before any destination is suggested." },
  { icon: "✦", title: "Every journey is thoughtfully designed", copy: "We shape possibilities around the people, pace and moments that matter." },
  { icon: "↗", title: "Honest advice over quick sales", copy: "We are clear about what fits, what needs checking and where a compromise exists." },
  { icon: "◎", title: "Personal support from your Journey Designer", copy: "A real person remains responsible for turning a possibility into a considered plan." },
] as const;

const inspiration = [
  { title: "Hidden sunrise experiences", copy: "Start a day somewhere still enough to remember it properly.", image: "/images/journey-passport/travel-styles/photography.webp" },
  { title: "Family-friendly escapes", copy: "Create room for every generation to enjoy the journey together.", image: "/images/journey-passport/companions/family.webp" },
  { title: "Slow travel ideas", copy: "Choose fewer places, stay a little longer and let the journey unfold.", image: "/images/journey-passport/travel-styles/relaxation.webp" },
  { title: "Weekend inspiration", copy: "A short change of scene can be the beginning of something restorative.", image: "/images/journey-passport/timing/within-next-month.webp" },
] as const;

const homepageInspiration = inspiration.slice(0, 3);

export default function HomepageExperience() {
  return (
    <div className="bg-[#FFFDFC] text-[#2A211C]">
      <section className="layout-section" aria-labelledby="journey-invitations-heading">
        <div className="layout-container">
          <div className="layout-section-heading"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#B72027]">Begin with what matters</p><h2 id="journey-invitations-heading" className="mt-4 text-balance font-serif text-4xl leading-[1.06] tracking-[-0.045em] sm:text-5xl">What kind of time are you hoping to make?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#2A211C]">You do not need every detail yet. Begin with the feeling, the people or the moment that is calling you.</p></div>
          <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {homepageInvitations.map((invitation, index) => <article key={invitation.title} className={`group relative min-h-[27rem] overflow-hidden rounded-[2rem] bg-[#2A211C] shadow-[0_18px_45px_rgba(86,55,22,0.14)] ${index === 0 ? "md:col-span-2 lg:col-span-1" : ""}`}><Image src={invitation.image} alt={invitation.alt} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(28,17,9,.92),rgba(28,17,9,.12)_76%)]" aria-hidden="true"/><div className="absolute inset-x-0 bottom-0 px-8 pb-9 pt-16 text-white"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[#F5951C]">A journey invitation</p><h3 className="mt-4 font-serif text-3xl leading-[1.1] tracking-[-0.04em]">{invitation.title}</h3><p className="mt-4 max-w-sm text-sm leading-7 text-white/85">{invitation.copy}</p><Link href={`/journey-passport?experience=${encodeURIComponent(invitation.title)}`} className="mt-6 inline-flex text-sm font-bold text-[#F5951C] transition hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#F5951C]">Explore this experience <span aria-hidden="true">→</span></Link></div></article>)}
          </div>
          <div className="mt-10 text-center"><Link href="/experiences" className="inline-flex rounded-full border border-[#280336] bg-white/55 px-6 py-3 text-sm font-bold text-[#4A2062] transition hover:bg-[#280336] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#280336]">Explore All Experiences <span aria-hidden="true" className="ml-2">→</span></Link></div>
        </div>
      </section>

      <section className="bg-[#FFFDFC] layout-section" aria-labelledby="destinations-heading"><div className="layout-container"><div className="layout-section-heading"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#B72027]">Places with possibility</p><h2 id="destinations-heading" className="mt-4 text-balance font-serif text-4xl leading-[1.06] tracking-[-0.045em] sm:text-5xl">Some places are worth beginning with.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#2A211C]">These are not packages or promises. They are thoughtful starting points for a conversation about what could fit.</p></div><div className="mx-auto mt-12 grid max-w-[72rem] gap-6 sm:grid-cols-2 lg:grid-cols-4">{destinations.map((destination)=><article key={destination.name} className="group flex flex-col overflow-hidden rounded-[1.75rem] bg-[#2A211C] shadow-[0_14px_35px_rgba(84,52,17,.14)]"><div className="relative aspect-[4/3] overflow-hidden"><Image src={destination.image} alt={`Travel inspiration for ${destination.name}`} fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/></div><div className="flex flex-1 flex-col px-7 pb-8 pt-7 text-white"><p className="text-[0.68rem] font-bold uppercase leading-5 tracking-[.14em] text-[#F5951C]">{destination.region}</p><h3 className="mt-3 font-serif text-3xl leading-[1.1]">{destination.name}</h3><p className="mt-4 text-sm leading-7 text-white/82">{destination.copy}</p><Link href={`/destinations#${destination.slug}`} className="mt-auto inline-flex pt-6 text-sm font-bold text-[#F5951C] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#F5951C]">Discover destination <span aria-hidden="true" className="ml-2">→</span></Link></div></article>)}</div><div className="mt-10 text-center"><Link href="/destinations" className="inline-flex rounded-full border border-[#280336] bg-white/55 px-6 py-3 text-sm font-bold text-[#4A2062] transition hover:bg-[#280336] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#280336]">Explore All Destinations <span aria-hidden="true" className="ml-2">→</span></Link></div></div></section>

      <section className="layout-section" aria-labelledby="trust-heading"><div className="layout-container grid gap-12 lg:grid-cols-[.8fr_1.5fr]"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#B72027]">Travel confidence</p><h2 id="trust-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-0.045em] sm:text-5xl">A journey begins with being understood.</h2><p className="mt-6 leading-8 text-[#2A211C]">We do not begin with what is easiest to sell. We begin with the person taking the journey.</p></div><div className="grid gap-4 sm:grid-cols-2">{trustPoints.map((point)=><article key={point.title} className="rounded-[1.5rem] border border-[#e4d2b5] bg-white p-7 shadow-[0_10px_28px_rgba(91,55,18,.06)]"><span aria-hidden="true" className="grid size-11 place-items-center rounded-full bg-[#f5e4c5] text-xl text-[#986328]">{point.icon}</span><h3 className="mt-6 text-xl font-semibold tracking-[-.02em]">{point.title}</h3><p className="mt-3 text-sm leading-7 text-[#2A211C]">{point.copy}</p></article>)}</div></div></section>

      <TravellerStories />

      <InspirationSurface className="layout-section" aria-labelledby="inspiration-heading"><div className="layout-container"><div className="layout-section-heading"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#B72027]">Travel inspiration</p><h2 id="inspiration-heading" className="mt-4 font-serif text-4xl leading-[1.06] tracking-[-0.045em] sm:text-5xl">A few ideas to carry with you.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-[#2A211C]">Inspiration is not an itinerary. It is a way to notice the kind of experience you may be ready for.</p></div><div className="mx-auto mt-12 grid max-w-[72rem] gap-5 md:grid-cols-2 lg:grid-cols-3">{homepageInspiration.map((item)=><Link key={item.title} href="/travel-inspiration" className="group relative block min-h-[27rem] overflow-hidden rounded-[2rem] bg-[#2A211C] shadow-[0_18px_45px_rgba(86,55,22,0.14)] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#F5951C]"><Image src={item.image} alt={`Travel inspiration: ${item.title}`} fill sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw" className="object-cover transition duration-700 group-hover:scale-105 motion-reduce:transition-none motion-reduce:group-hover:scale-100"/><div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(28,17,9,.92),rgba(28,17,9,.12)_76%)]" aria-hidden="true"/><div className="absolute inset-x-0 bottom-0 px-8 pb-9 pt-16 text-white"><h3 className="font-serif text-2xl leading-[1.15]">{item.title}</h3><p className="mt-4 text-sm leading-7 text-white/85">{item.copy}</p><span className="mt-6 inline-flex text-sm font-bold text-[#F5951C]">Explore this idea <span aria-hidden="true" className="ml-2">→</span></span></div></Link>)}</div><div className="text-center"><Link href="/travel-inspiration" className="mt-10 inline-flex rounded-full border border-[#280336] bg-white/55 px-6 py-3 text-sm font-bold text-[#4A2062] transition hover:bg-[#280336] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#280336]">Explore All Inspiration <span aria-hidden="true" className="ml-2">→</span></Link></div></div></InspirationSurface>

      <section className="layout-section" aria-labelledby="about-preview-heading"><div className="layout-container grid overflow-hidden rounded-[2rem] bg-[linear-gradient(125deg,#f6e2bd,#FFFDFC_55%,#ead6b1)] lg:grid-cols-[1.1fr_.9fr]"><div className="p-8 sm:p-12 lg:p-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#B72027]">Our promise to you</p><h2 id="about-preview-heading" className="mt-4 max-w-xl font-serif text-4xl leading-[1.03] tracking-[-.045em] sm:text-5xl">More Than a Trip. It’s an Experience.</h2><p className="mt-6 max-w-xl leading-8 text-[#2A211C]">Every traveller is unique. Every journey should be too. We listen before selling, guide honestly and keep people at the centre of every decision.</p><Link href="/about" className="mt-8 inline-flex rounded-full bg-[#280336] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#4A2062] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#280336]">Learn more about us <span aria-hidden="true" className="ml-2">→</span></Link></div><div className="relative min-h-[20rem]"><Image src="/images/homepage/our-promise-planning.webp" alt="A journey planner listening to a traveller while they review a map together" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover"/></div></div></section>

      <section className="bg-[#FFFDFC] layout-section" aria-labelledby="contact-preview-heading"><div className="layout-container grid gap-10 rounded-[2rem] bg-white p-8 shadow-[0_14px_40px_rgba(86,55,22,.08)] sm:p-12 lg:grid-cols-[1.05fr_.95fr] lg:p-16"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#B72027]">Begin a conversation</p><h2 id="contact-preview-heading" className="mt-4 font-serif text-4xl leading-[1.03] tracking-[-.045em] sm:text-5xl">When you are ready, we are here.</h2><p className="mt-5 max-w-xl leading-8 text-[#2A211C]">Tell us what is on your mind. A Journey Designer can help you take the next thoughtful step.</p><Link href="/journey-passport" className="mt-8 inline-flex rounded-full bg-[#280336] px-7 py-3 text-sm font-bold text-white transition hover:bg-[#4A2062] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#280336]">Start planning your journey <span aria-hidden="true" className="ml-2">→</span></Link></div><address className="not-italic text-[#2A211C]"><dl className="grid gap-5"><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#B72027]">WhatsApp</dt><dd className="mt-2"><WhatsAppLink compact/></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#B72027]">Phone</dt><dd className="mt-1"><a href={siteContact.primaryPhoneHref} className="inline-flex min-h-11 items-center font-semibold text-[#2A211C] underline decoration-[#F36523] underline-offset-4">{siteContact.phoneDisplay}</a></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#B72027]">Email</dt><dd className="mt-1"><a href={siteContact.emailHref} className="inline-flex min-h-11 items-center font-semibold text-[#2A211C] underline decoration-[#F36523] underline-offset-4">{siteContact.email}</a></dd></div><div><dt className="text-xs font-bold uppercase tracking-[.14em] text-[#B72027]">Office hours</dt><dd className="mt-1">Monday–Saturday<br/>10:00 AM–7:00 PM IST</dd></div></dl></address></div></section>
    </div>
  );
}
