import type { Metadata } from "next";
import PublicPage from "@/components/layout/PublicPage";
import { EditorialCardGrid, EditorialContinuation, type EditorialCardItem } from "@/components/discovery/EditorialCards";
export const metadata: Metadata = { title: "Experiences", description: "Explore journeys through the moments you hope to make." };
const experiences: EditorialCardItem[] = [
  { title: "Memory Makers", label: "Moments to carry home", copy: "Think of golden-hour walks, a table worth lingering at and a view that changes how a day feels.", image: "/images/journey-passport/travel-styles/photography.webp", alt: "Traveller capturing a meaningful travel memory", prompt: "What would you love to remember most?", passportHref: "/journey-passport?experience=Memory%20Makers", passportLabel: "Explore This Experience" },
  { title: "Celebration Moments", label: "Milestones made meaningful", copy: "A birthday, anniversary or simply time together can become a journey with the right setting and care.", image: "/images/journey-passport/travel-styles/celebrations.webp", alt: "Travellers sharing a celebration", prompt: "What is worth marking properly?", passportHref: "/journey-passport?experience=Celebration%20Moments", passportLabel: "Explore This Experience" },
  { title: "Family Time", label: "Together, at your own pace", copy: "Make space for generations, easy shared moments and time that does not feel over-scheduled.", image: "/images/journey-passport/companions/family.webp", alt: "Family spending time together while travelling", prompt: "Who would make this journey complete?", passportHref: "/journey-passport?experience=Family%20Time", passportLabel: "Explore This Experience" },
  { title: "Global Escapes", label: "A different way of seeing", copy: "Step into a new rhythm through local food, culture, neighbourhoods and a little healthy unfamiliarity.", image: "/images/journey-passport/dream-journeys/city-discovery.webp", alt: "Traveller discovering a new city", prompt: "What kind of new perspective are you looking for?", passportHref: "/journey-passport?experience=Global%20Escapes", passportLabel: "Explore This Experience" },
  { title: "Nature & Serenity", label: "Room to breathe", copy: "Imagine quieter mornings, wide views and enough space to return feeling more like yourself.", image: "/images/journey-passport/travel-styles/nature.webp", alt: "Quiet natural landscape for a slower journey", prompt: "Where would you like to slow down?", passportHref: "/journey-passport?experience=Nature%20%26%20Serenity", passportLabel: "Explore This Experience" },
  { title: "Weekend Getaways", label: "A thoughtful pause", copy: "A few days can hold a reset: a coastal stay, a hill drive, a long meal or a change of scenery.", image: "/images/journey-passport/timing/within-next-month.webp", alt: "Traveller preparing for a short escape", prompt: "What would make the next weekend feel different?", passportHref: "/journey-passport?experience=Weekend%20Getaways", passportLabel: "Explore This Experience" },
];
export default function ExperiencesPage(){return <PublicPage eyebrow="Experiences" title="What kind of experience could we create together?" intro="The feeling comes first. These are invitations to imagine, not fixed packages or promises."><section className="layout-section"><div className="layout-container"><div className="layout-section-heading mb-12"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#2A211C]">Begin with a feeling</p><h2 className="mt-4 text-balance font-serif text-4xl leading-[1.08] tracking-[-.04em] sm:text-5xl">A journey can be many things. It should feel like yours.</h2><p className="mx-auto mt-5 max-w-2xl leading-8 text-[#2A211C]">Your Journey Designer will use these possibilities as a starting point, then shape the details around the people and moments that matter.</p></div><EditorialCardGrid items={experiences}/></div></section><EditorialContinuation eyebrow="Your experience, considered" title="The best journeys begin with a little understanding." copy="Tell us the experience you are drawn to. We will help turn it into a thoughtful possibility." label="Plan My Experience"/></PublicPage>}
