import Image from "next/image";
import type { RefObject } from "react";

import { journeyMoments, travelStyleOptions } from "@/config/journey-passport.config";
import { JOURNEY_ENTRY_ADVISORY } from "@/lib/journey-passport/entry-context";
import { journeyPassportBlurPlaceholder } from "@/lib/journey-passport/image-blur-placeholders";
import type { DestinationMode, JourneyMoment, JourneyPassportState } from "@/types/journey-passport.types";

import { SelectionCard } from "./SelectionCard";

type HeadingRef = RefObject<HTMLHeadingElement | null>;

// EWP-R1.2-WS4-001: same content-aware blur-preview treatment as SelectionCard
// (see image-blur-placeholders.ts) applied to the Welcome screen's hero photo.
const WELCOME_IMAGE_SRC = "/images/journey-passport/journey-passport-welcome.webp";
const welcomeBlurDataURL = journeyPassportBlurPlaceholder(WELCOME_IMAGE_SRC);

export function MomentHeading({ headingRef, moment }: { headingRef: HeadingRef; moment: JourneyMoment }) {
  return <div className="mx-auto max-w-3xl text-center"><p className="text-[0.69rem] font-bold uppercase tracking-[0.18em] text-[#2A211C]">Chapter {moment.number - 1} · {moment.navigationLabel}</p><h1 ref={headingRef} tabIndex={-1} className="mt-4 text-balance text-[clamp(2.1rem,5vw,4.25rem)] font-semibold leading-[1.12] tracking-[-0.04em] text-[#2A211C] outline-none">{moment.title}</h1>{moment.description ? <p className="mx-auto mt-5 max-w-2xl text-[clamp(1rem,1.4vw,1.125rem)] leading-8 text-[#2A211C]">{moment.description}</p> : null}</div>;
}

export function WelcomeMoment({ onBegin }: { onBegin: () => void }) {
  return <section className="relative min-h-[clamp(34rem,68svh,42rem)] overflow-hidden rounded-[2rem] bg-[#2A211C] shadow-[0_30px_90px_rgba(69,39,15,0.22)] sm:rounded-[2.5rem]"><Image src={WELCOME_IMAGE_SRC} alt="Traveller holding a journal and looking from a train window towards a sunlit landscape" fill priority sizes="(max-width: 1440px) 100vw, 88rem" {...(welcomeBlurDataURL ? { placeholder: "blur" as const, blurDataURL: welcomeBlurDataURL } : {})} className="object-cover object-[38%_center] sm:object-center" /><div className="absolute inset-0 bg-[linear-gradient(270deg,rgba(24,15,8,0.9),rgba(24,15,8,0.62)_54%,rgba(24,15,8,0.16)),linear-gradient(0deg,rgba(24,15,8,0.76),transparent_65%)]" aria-hidden="true" /><div className="relative ml-auto flex min-h-[clamp(34rem,68svh,42rem)] w-full flex-col justify-end p-7 sm:p-12 lg:w-[60%] lg:justify-center lg:p-16"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#F5951C]">A thoughtfully designed beginning</p><h1 className="mt-5 text-balance text-[clamp(2.65rem,6.5vw,5rem)] font-semibold leading-[1.04] tracking-[-0.05em] text-white">Welcome to Your Journey Passport</h1><p className="mt-5 max-w-xl text-lg leading-8 text-white/90">Every memorable journey begins with understanding the traveller behind it.</p><p className="mt-3 max-w-2xl text-base leading-7 text-white/80">We take the time to understand what matters to you, so we can discover experiences that feel truly yours.</p><button type="button" onClick={onBegin} className="mt-8 min-h-12 w-fit rounded-full bg-[#F5951C] px-8 py-3 text-sm font-bold text-[#2A211C] shadow-[0_12px_28px_rgba(0,0,0,0.2)] transition hover:-translate-y-0.5 hover:bg-[#F5951C] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#F5951C] motion-reduce:transition-none motion-reduce:hover:translate-y-0">Begin My Journey <span aria-hidden="true">→</span></button></div></section>;
}

export function AboutYouMoment({ headingRef, moment, name, onChange }: { headingRef: HeadingRef; moment: JourneyMoment; name: string; onChange: (value: string) => void }) {
  const invalid = name.length > 0 && (name.trim().length < 2 || !/\p{L}/u.test(name));
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} /><div className="mx-auto mt-9 max-w-2xl rounded-[2rem] border border-[#e6d5bb] bg-white/85 p-6 shadow-[0_16px_40px_rgba(93,59,21,0.08)] sm:p-10"><label htmlFor="passport-name" className="block text-lg font-semibold text-[#2A211C]">What should we call you?</label><input id="passport-name" name="name" type="text" value={name} maxLength={80} onChange={(event) => onChange(event.target.value.replace(/[\r\n]+/g, " "))} autoComplete="name" aria-invalid={invalid || undefined} aria-describedby="passport-name-help" className="mt-5 min-h-14 w-full rounded-2xl border border-[#d8c4a7] bg-[#FFFDFC] px-5 text-lg text-[#2A211C] outline-none transition focus:border-[#2A211C] focus:ring-4 focus:ring-[#FFFDFC]" /><div id="passport-name-help" className="mt-4 flex flex-wrap justify-between gap-2 text-sm leading-6 text-[#2A211C]"><span>{invalid ? "Please share the name you’d like us to use." : "We’ll use your name to make every conversation feel personal."}</span><span aria-label={`${name.length} of 80 characters`}>{name.length}/80</span></div></div></section>;
}

export function SingleChoiceMoment({ headingRef, moment, value, showEntryAdvisory = false, onChange }: { headingRef: HeadingRef; moment: JourneyMoment; value: string; showEntryAdvisory?: boolean; onChange: (value: string) => void }) {
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} />{showEntryAdvisory ? <p role="status" className="mx-auto mt-6 max-w-3xl rounded-2xl border border-[#e1ceb0] bg-[#f8eddd] px-5 py-4 text-center text-sm text-[#2A211C]">{JOURNEY_ENTRY_ADVISORY}</p> : null}<div role="radiogroup" aria-label={moment.title} className={`mx-auto grid max-w-6xl gap-4 ${showEntryAdvisory ? "mt-6" : "mt-9"} ${moment.id === "dream-journey" ? "md:grid-cols-2 lg:grid-cols-3" : "md:grid-cols-2 lg:grid-cols-3"}`}>{(moment.options ?? []).map((option) => <SelectionCard key={option.value} option={option} selected={value === option.value} onSelect={() => onChange(option.value)} />)}</div></section>;
}

export function TravelStyleMoment({ headingRef, moment, values, onToggle }: { headingRef: HeadingRef; moment: JourneyMoment; values: string[]; onToggle: (value: string) => void }) {
  const count = values.length;
  const counter = count === 0 ? "0 of 3 selected" : count === 1 ? "1 of 3 — a lovely start." : count === 2 ? "2 of 3 — your journey is taking shape." : "Perfect. We can already picture the kind of experience you’re looking for.";
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} /><p role="status" aria-live="polite" className={`mx-auto mt-6 max-w-3xl rounded-2xl px-4 py-3 text-center text-sm font-semibold ${count === 3 ? "bg-[#edf7ed] text-[#27643a]" : "bg-[#f8eddd] text-[#2A211C]"}`}>{counter}</p><div role="group" aria-label={moment.title} className="mx-auto mt-6 grid max-w-5xl gap-3.5 sm:grid-cols-2 lg:grid-cols-3">{(moment.options ?? []).map((option) => { const selected = values.includes(option.value); return <SelectionCard key={option.value} option={option} compact multi selected={selected} unavailable={count === 3 && !selected} onSelect={() => onToggle(option.value)} />; })}</div></section>;
}

export function TimingMoment({ headingRef, moment, state, onUpdate }: { headingRef: HeadingRef; moment: JourneyMoment; state: JourneyPassportState; onUpdate: (value: Partial<JourneyPassportState>) => void }) {
  const now = new Date();
  const today = new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
  const dateInvalid = state.timing === "Exact Dates" && Boolean((state.startDate && state.startDate < today) || (state.startDate && state.endDate && state.endDate <= state.startDate));
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} /><div role="radiogroup" aria-label="Travel timing" className="mx-auto mt-9 grid max-w-6xl gap-3.5 sm:grid-cols-2 lg:grid-cols-6">{(moment.options ?? []).map((option, index) => <SelectionCard key={option.value} option={option} compact className={index < 3 ? "lg:col-span-2" : "lg:col-span-3"} selected={state.timing === option.value} onSelect={() => onUpdate({ timing: option.value })} />)}</div>{state.timing === "I’m Flexible" ? <p role="status" className="mx-auto mt-6 max-w-3xl rounded-2xl bg-[#f8eddd] px-5 py-4 text-center text-sm text-[#2A211C]">Keeping your travel dates flexible gives us more possibilities to explore.</p> : null}{state.timing === "Exact Dates" ? <div className="journey-passport-reveal mx-auto mt-6 max-w-3xl rounded-[1.5rem] border border-[#e1ceb0] bg-[#FFFDFC] p-5 sm:p-6"><p className="mb-5 text-sm font-semibold text-[#2A211C]">Wonderful. Share the dates you already have in mind.</p><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-[#2A211C]">Departure date<input type="date" value={state.startDate} min={today} onChange={(event) => onUpdate({ startDate: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c4a7] bg-white px-3 text-[#2A211C] focus:outline-2 focus:outline-offset-2 focus:outline-[#2A211C]" /></label><label className="text-sm font-semibold text-[#2A211C]">Return date<input type="date" value={state.endDate} min={state.startDate || today} aria-invalid={dateInvalid || undefined} aria-describedby={dateInvalid ? "date-range-error" : undefined} onChange={(event) => onUpdate({ endDate: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c4a7] bg-white px-3 text-[#2A211C] focus:outline-2 focus:outline-offset-2 focus:outline-[#2A211C]" /></label></div>{dateInvalid ? <p id="date-range-error" className="mt-4 text-sm font-medium text-[#a1463c]">Your return should come after your departure.</p> : null}</div> : null}</section>;
}

export function PaceAndTimingMoment({ headingRef, moment, state, showEntryAdvisory = false, onUpdate, onToggle }: { headingRef: HeadingRef; moment: JourneyMoment; state: JourneyPassportState; showEntryAdvisory?: boolean; onUpdate: (value: Partial<JourneyPassportState>) => void; onToggle: (value: string) => void }) {
  const now = new Date();
  const today = new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
  const count = state.travelStyles.length;
  const dateInvalid = state.timing === "Exact Dates" && Boolean((state.startDate && state.startDate < today) || (state.startDate && state.endDate && state.endDate <= state.startDate));

  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} />
    {showEntryAdvisory ? <p role="status" className="mx-auto mt-6 max-w-3xl rounded-2xl border border-[#e1ceb0] bg-[#f8eddd] px-5 py-4 text-center text-sm text-[#2A211C]">{JOURNEY_ENTRY_ADVISORY}</p> : null}
    <div className={`mx-auto max-w-5xl rounded-[2rem] border border-[#e6d5bb] bg-white/80 p-5 shadow-[0_16px_40px_rgba(93,59,21,0.07)] sm:p-8 ${showEntryAdvisory ? "mt-6" : "mt-9"}`}>
      <div className="flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2A211C]">First, choose your rhythm</p><h2 className="mt-2 text-xl font-semibold text-[#2A211C]">What memories would you love to bring back?</h2></div><p role="status" aria-live="polite" className="text-sm font-semibold text-[#2A211C]">{count} of 3 selected</p></div>
      <div role="group" aria-label="Travel styles—choose up to three" className="mt-5 flex flex-wrap gap-2.5">{travelStyleOptions.map((option) => { const selected = state.travelStyles.includes(option.value); const unavailable = count === 3 && !selected; return <button key={option.value} type="button" aria-pressed={selected} disabled={unavailable} onClick={() => onToggle(option.value)} className={`min-h-11 rounded-full border px-4 py-2 text-sm font-semibold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#2A211C] ${selected ? "border-[#F5951C] bg-[#F5951C] text-[#2A211C]" : "border-[#dcc8aa] bg-[#fffaf1] text-[#2A211C] hover:border-[#b9823f]"} disabled:cursor-not-allowed disabled:opacity-45`}><span aria-hidden="true" className="mr-1.5">{selected ? "✓" : "+"}</span>{option.label}</button>; })}</div>
      <div className="my-7 h-px bg-[#eadcc7]" aria-hidden="true" />
      <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2A211C]">Then, choose your timing</p><h2 className="mt-2 text-xl font-semibold text-[#2A211C]">When would you love this journey to begin?</h2></div>
      <div role="radiogroup" aria-label="Travel timing" className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{(moment.options ?? []).map((option, index) => <SelectionCard key={option.value} option={option} compact className={index < 3 ? "lg:col-span-2" : "lg:col-span-3"} selected={state.timing === option.value} onSelect={() => onUpdate({ timing: state.timing === option.value ? "" : option.value })} />)}</div>
      {state.timing === "I’m Flexible" ? <p role="status" className="mt-5 rounded-2xl bg-[#f8eddd] px-5 py-4 text-center text-sm text-[#2A211C]">Keeping your travel dates flexible gives us more possibilities to explore.</p> : null}
      {state.timing === "Exact Dates" ? <div className="journey-passport-reveal mt-5 rounded-[1.5rem] border border-[#e1ceb0] bg-[#FFFDFC] p-5 sm:p-6"><p className="mb-5 text-sm font-semibold text-[#2A211C]">Wonderful. Share the dates you already have in mind.</p><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-[#2A211C]">Departure date<input type="date" value={state.startDate} min={today} onChange={(event) => onUpdate({ startDate: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c4a7] bg-white px-3 text-[#2A211C] focus:outline-2 focus:outline-offset-2 focus:outline-[#2A211C]" /></label><label className="text-sm font-semibold text-[#2A211C]">Return date<input type="date" value={state.endDate} min={state.startDate || today} aria-invalid={dateInvalid || undefined} aria-describedby={dateInvalid ? "date-range-error" : undefined} onChange={(event) => onUpdate({ endDate: event.target.value })} className="mt-2 min-h-12 w-full rounded-xl border border-[#d8c4a7] bg-white px-3 text-[#2A211C] focus:outline-2 focus:outline-offset-2 focus:outline-[#2A211C]" /></label></div>{dateInvalid ? <p id="date-range-error" className="mt-4 text-sm font-medium text-[#a1463c]">Your return should come after your departure.</p> : null}</div> : null}
    </div>
  </section>;
}

export function DestinationMoment({ headingRef, moment, state, onMode, onDestination }: { headingRef: HeadingRef; moment: JourneyMoment; state: JourneyPassportState; onMode: (value: DestinationMode) => void; onDestination: (value: string) => void }) {
  const known = state.entryContext.destination;
  const displayedMoment = known ? { ...moment, title: "Do you already have something in mind?" } : moment;
  const choices = known ? [
    { value: "known", label: "Yes", description: `${known} is ready below, and you can edit it anytime.`, imageSrc: "/images/journey-passport/destination-preferences/destination-known.webp", imageAlt: "Traveller confidently reviewing a map for a journey already chosen" },
    { value: "discovery", label: "Surprise Me", description: "Invite us to widen the search and suggest somewhere special.", imageSrc: "/images/journey-passport/destination-preferences/guided-discovery.webp", imageAlt: "Traveller looking across an open landscape toward new possibilities" },
  ] : [
    { value: "known", label: "I already have somewhere in mind", description: "Share the place—or kind of place—you are imagining.", imageSrc: "/images/journey-passport/destination-preferences/destination-known.webp", imageAlt: "Traveller confidently reviewing a map for a journey already chosen" },
    { value: "discovery", label: "Help me discover somewhere special", description: "Let us begin with what matters to you.", imageSrc: "/images/journey-passport/destination-preferences/guided-discovery.webp", imageAlt: "Traveller looking across an open landscape toward new possibilities" },
  ];
  const selectedValue = state.destinationMode;
  const select = (value: string) => { if (value === "discovery") onMode("discovery"); else { onMode("known"); if (known && !state.destination.trim()) onDestination(known); } };
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={displayedMoment} />{known ? <p className="mx-auto mt-6 max-w-3xl rounded-2xl bg-[#f8eddd] px-5 py-4 text-center text-sm text-[#2A211C]">We carried {known} forward from the destination you were exploring. Every choice remains yours to change.</p> : null}<div role="radiogroup" aria-label="Destination preference" className="mx-auto mt-7 grid max-w-4xl gap-4 md:grid-cols-2">{choices.map((choice) => <SelectionCard key={choice.value} option={choice} compact selected={selectedValue === choice.value} onSelect={() => select(choice.value)} />)}</div>{state.destinationMode === "known" ? <div className="journey-passport-reveal mx-auto mt-6 max-w-2xl rounded-[1.5rem] border border-[#e1ceb0] bg-white/85 p-5 sm:p-6"><label htmlFor="destination-search" className="text-sm font-semibold text-[#2A211C]">Where would you love to go?</label><input id="destination-search" name="journey-destination" type="text" autoComplete="off" value={state.destination} maxLength={100} onChange={(event) => onDestination(event.target.value.replace(/[\r\n]+/g, " "))} className="mt-2 min-h-14 w-full rounded-xl border border-[#d8c4a7] bg-[#FFFDFC] px-4 text-base text-[#2A211C] focus:outline-2 focus:outline-offset-2 focus:outline-[#2A211C]" placeholder="A place, region or kind of destination" /><p className="mt-3 text-sm leading-6 text-[#2A211C]">Write any destination in your own words. A specific place or an idea such as “somewhere warm in Europe” is perfect.</p></div> : null}</section>;
}

const list = (values: string[]) => values.length < 2 ? (values[0] ?? "") : values.length === 2 ? `${values[0]} and ${values[1]}` : `${values.slice(0, -1).join(", ")}, and ${values.at(-1)}`;
const displayDate = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
const companionSummary = (companion: string) => companion === "Solo" ? "solo" : companion === "Couple" ? "as a couple" : companion === "Business" ? "with colleagues" : `with ${companion.toLowerCase()}`;

export function DiscoverMoment({ headingRef, moment, state }: { headingRef: HeadingRef; moment: JourneyMoment; state: JourneyPassportState }) {
  const timing = state.timing === "Exact Dates" ? `Travelling from ${displayDate(state.startDate)} to ${displayDate(state.endDate)}.` : state.timing === "I’m Flexible" ? "Keeping the timing flexible." : `Hoping to travel ${state.timing.toLowerCase()}.`;
  const items = [`Travelling ${companionSummary(state.companion)}.`, `Dreaming of a ${state.dreamJourney.toLowerCase()}.`, `Drawn to ${list(state.travelStyles.map((value) => value.toLowerCase()))}.`, timing, state.destinationMode === "discovery" ? "Open to discovering somewhere special." : `Beginning with ${state.destination.trim()}.`];
  return <section className="pt-8"><MomentHeading headingRef={headingRef} moment={moment} /><div className="mx-auto mt-8 max-w-4xl rounded-[2rem] border border-[#e7d6bd] bg-[linear-gradient(135deg,#FFFDFC,#FFFDFC)] p-6 shadow-[0_20px_44px_rgba(97,61,22,0.1)] sm:p-10"><p className="text-sm leading-7 text-[#745d45]">{state.name.trim()}, here is the beginning of a journey designed around you.</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="flex gap-3 rounded-xl border border-white/80 bg-white/75 p-4 text-[#2A211C]"><span aria-hidden="true" className="text-[#F5951C]">✦</span><span>{item}</span></li>)}</ul><p className="mt-7 text-lg font-semibold text-[#2A211C]">Your Journey Director will begin with the choices that matter most to you.</p></div></section>;
}

export const momentsById = Object.fromEntries(journeyMoments.map((moment) => [moment.id, moment])) as Record<JourneyPassportState["currentMoment"], JourneyMoment>;
