export const siteBrand = {
  name: "Search My Vacation",
  shortName: "SMV",
  tagline: "More than a trip. It's an experience.",
  accessibleLabel:
    "Search My Vacation — More than a trip. It's an experience.",
  colours: {
    fuchsia: "#B41D8E",
    crimson: "#B72027",
    aubergine: "#280336",
    amber: "#F5951C",
    orange: "#F36523",
    espresso: "#2A211C",
    cream: "#FFFDFC",
  },
  assets: {
    headerLightSurface: "/brand/official/web/web-header-light-bg-transparent.png",
    headerDarkSurface: "/brand/official/web/web-header-dark-bg-transparent.png",
    fullLightSurface: "/brand/official/logo/horizon-wordmark-horizontal-dark-text-transparent.png",
    fullDarkSurface: "/brand/official/logo/horizon-wordmark-horizontal-light-text-transparent.png",
    compactLightSurface: "/brand/official/logo/horizon-wordmark-short-dark-text-transparent.png",
    compactDarkSurface: "/brand/official/logo/horizon-wordmark-short-light-text-transparent.png",
    primaryLockup: "/brand/official/logo/original-supplied-lockup-espresso-bg.png",
    iconMark: "/brand/official/logo/icon-mark-transparent-2000px.png",
    favicon: "/brand/official/favicon/favicon.ico",
    favicon16: "/brand/official/favicon/favicon-16.png",
    favicon32: "/brand/official/favicon/favicon-32.png",
    appleTouchIcon: "/brand/official/favicon/apple-touch-icon-180.png",
    appIcon192: "/brand/official/favicon/favicon-192.png",
    appIcon512: "/brand/official/app/app-icon-rounded-512.png",
    openGraphImage: "/brand/official/web/social-share-og-image-1200x630.png",
    emailLogo: "/brand/official/email/email-signature-logo-transparent.png",
  },
} as const;
