import type { Metadata } from "next";
import PublicPage from "@/components/layout/PublicPage";
import { EditorialCardGrid, EditorialContinuation, type EditorialCardItem } from "@/components/discovery/EditorialCards";

export const metadata: Metadata = { title: "Destinations", description: "Discover Release 1 destinations through the experience you hope to create." };

const india: EditorialCardItem[] = [
  ["Agra", "India · Heritage", "For timeless architecture, quiet wonder and a journey with perspective.", "city-discovery"], ["Amritsar", "India · Culture", "For generous hospitality, living history and meaningful local connection.", "culture-heritage"], ["Andaman", "India · Islands", "For clear water, open skies and days that move at the pace of the sea.", "beaches-islands"], ["Goa", "India · Coast", "For sunlit pauses, culture and a relaxed rhythm by the shore.", "tropical-escape"], ["Gujarat", "India · Heritage & nature", "For craft, colour and landscapes that reward curiosity.", "culture-heritage"], ["Himachal Pradesh", "India · Mountains", "For fresh air, quieter mornings and room to reset.", "mountain-retreat"], ["Karnataka", "India · Culture & nature", "For a journey that moves between heritage, coffee country and green space.", "nature"], ["Kashmir", "India · Mountains & valleys", "For wide landscapes and a complete change of pace.", "mountain-retreat"], ["Kerala", "India · Backwaters & hills", "For unhurried days shaped by water, green space and gentle comfort.", "kerala"], ["Northeast", "India · Hills & culture", "For slower roads, layered local stories and nature-led discovery.", "nature"], ["Pondicherry", "India · Coast & culture", "For a small change of rhythm between cafés, coast and calm streets.", "city-discovery"], ["Assam", "India · River & wildlife", "For tea country, river landscapes and a closer connection with nature.", "wildlife"], ["Rajasthan", "India · Heritage", "For colour, history and stories that unfold at their own pace.", "culture-heritage"], ["Tamil Nadu", "India · Culture & coast", "For temple towns, local flavours and journeys with depth.", "food-dining"], ["Hyderabad", "India · Food & heritage", "For rich flavours, historic layers and vibrant city energy.", "food-dining"], ["Vizag", "India · Coast & hills", "For sea views, green hills and an easy coastal reset.", "beaches-islands"],
].map(([title, label, copy, image]) => toCard(title, label, copy, image));

const international: EditorialCardItem[] = [
  ["Bali", "Indonesia · Ritual & renewal", "For warm light, generous culture and moments of quiet discovery.", "bali"], ["Dubai", "United Arab Emirates · City & desert", "For polished stays, striking contrasts and celebratory energy.", "city-discovery"], ["Malaysia", "Malaysia · Cities & coast", "For easy variety between food, culture, rainforest and shoreline.", "food-dining"], ["Singapore", "Singapore · City & gardens", "For a smooth rhythm of design, food and green spaces.", "city-discovery"], ["Sri Lanka", "Sri Lanka · Coast & culture", "For tea country, coastline and stories that invite a slower look.", "tropical-escape"], ["Thailand", "Thailand · Islands & culture", "For warm hospitality, vibrant food and time by the water.", "beaches-islands"], ["Vietnam", "Vietnam · Culture & discovery", "For layered stories, vivid flavours and journeys full of perspective.", "adventure"],
].map(([title, label, copy, image]) => toCard(title, label, copy, image));

const wildlife: EditorialCardItem[] = [
  ["Wildlife experiences", "India · Nature-led journeys", "For journeys that make space for the natural world and patient observation.", "wildlife"], ["Kabini", "India · Forest", "For calm forest stays and the possibility of seeing life beyond the everyday.", "wildlife"], ["Corbett", "India · Forest & river", "For open landscapes, river air and a slower pace close to nature.", "nature"], ["Bandipur", "India · Forest", "For thoughtful time in a landscape shaped by conservation and quiet.", "wildlife"], ["Masinagudi", "India · Nilgiris", "For a gentle nature escape at the meeting point of hills and forest.", "nature"],
].map(([title, label, copy, image]) => toCard(title, label, copy, image));

function toCard(title: string, label: string, copy: string, image: string): EditorialCardItem {
  const images: Record<string, string> = { bali: "/images/journey-director/bali-ubud-golden-hour.jpg", kerala: "/images/journey-director/kerala-alleppey-golden-hour.jpg", "city-discovery": "/images/journey-passport/dream-journeys/city-discovery.webp", "culture-heritage": "/images/journey-passport/travel-styles/culture-heritage.webp", "beaches-islands": "/images/journey-passport/travel-styles/beaches-islands.webp", "tropical-escape": "/images/journey-passport/dream-journeys/tropical-escape.webp", "mountain-retreat": "/images/journey-passport/dream-journeys/mountain-retreat.webp", nature: "/images/journey-passport/travel-styles/nature.webp", wildlife: "/images/journey-passport/travel-styles/wildlife.webp", "food-dining": "/images/journey-passport/travel-styles/food-dining.webp", adventure: "/images/journey-passport/travel-styles/adventure.webp" };
  return { title, label, copy, image: images[image], alt: `Travel inspiration for ${title}` };
}

export default function DestinationsPage() { return <PublicPage eyebrow="Destinations" title="Where could this journey take you?" intro="Begin with the feeling you hope to find. Your Journey Director will help identify the destination that best supports it."><section className="px-6 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="India" title="A country of many different journeys." copy="From heritage and coast to hills, forests and island time—each place asks for a different kind of traveller story."/><EditorialCardGrid items={india}/><SectionHeading eyebrow="International" title="A world worth exploring thoughtfully." copy="These are Release 1 starting points for travellers ready to see somewhere new with confidence."/><EditorialCardGrid items={international}/><SectionHeading eyebrow="Nature and wildlife" title="For journeys led by the natural world." copy="The right wildlife journey values patience, respect for place and enough time to notice what is around you."/><EditorialCardGrid items={wildlife}/></div></section><EditorialContinuation eyebrow="A more personal beginning" title="Let the right destination follow the right conversation." copy="Share what matters to you, and your Journey Director will help find the possibility that fits." label="Find the journey that fits me"/></PublicPage>; }
function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="mb-9 mt-16 first:mt-0"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#96652b]">{eyebrow}</p><h2 className="mt-3 font-serif text-4xl tracking-[-.04em]">{title}</h2><p className="mt-4 max-w-2xl leading-7 text-[#705c47]">{copy}</p></div>; }
